require "json"

package = JSON.parse(File.read(File.join(__dir__, "package.json")))

Pod::Spec.new do |s|
  s.name         = "TaqlynSdk"
  s.version      = package["version"]
  s.summary      = package["description"]
  s.homepage     = "https://github.com/taqlyn/sdk-react-native"
  s.license      = package["license"] || "MIT"
  s.authors      = "Taqlyn"

  s.platforms    = { :ios => "16.0" }
  s.source       = { :git => "https://github.com/taqlyn/sdk-react-native.git", :tag => "#{s.version}" }

  s.source_files = [
    "ios/**/*.{swift}",
    "ios/**/*.{m,mm}",
    "cpp/**/*.{hpp,cpp}",
  ]

  # Generated by `bun run codegen` (npx nitrogen)
  nitrogen_rb = File.join(__dir__, "nitrogen/generated/ios/TaqlynSdk+autolinking.rb")
  if File.exist?(nitrogen_rb)
    load nitrogen_rb
    add_nitrogen_files(s)
  else
    Pod::UI.warn "TaqlynSdk: run `bun run codegen` in packages/sdk-react-native to generate nitrogen/ios bindings"
  end

  s.dependency "React-jsi"
  s.dependency "React-callinvoker"
  s.dependency "TaqlynSDK", "~> 0.1"

  install_modules_dependencies(s) if defined?(install_modules_dependencies)
end
